## Generate Test and TrainVal videoid_sentid lists

In [4]:
# import json
# anno_path = '/usr/local/extstore01/zahra/datasets/MSRVTT/train_val_annotation/train_val_videodatainfo.json'
# anno = json.load(open(anno_path, 'rb'))

# videoid_sentid = []
# for item in anno['sentences']:
#     vidid = str(item['video_id'])
#     sentid = str(item['sen_id'])
    
#     videoid_sentid.append(vidid+'_'+sentid)

# # from utils.sys_utils import dump_textfile
# # dump_textfile(videoid_sentid,'/usr/local/extstore01/zahra/datasets/MSRVTT/TrainVal_videoid_sentid.txt')

In [22]:
# import json
# anno_path = '/usr/local/extstore01/zahra/datasets/MSRVTT/test_videodatainfo/test_videodatainfo.json'
# anno = json.load(open(anno_path, 'rb'))

# videoid_sentid = []
# for item in anno['sentences']:
#     vidid = str(item['video_id'])
#     sentid = str(item['sen_id'])
    
#     videoid_sentid.append(vidid+'_'+sentid)
    
# # from utils.sys_utils import dump_textfile    
# # dump_textfile(videoid_sentid,'/usr/local/extstore01/zahra/datasets/MSRVTT/Test_videoid_sentid.txt')

## Load MSRVTT dataset

In [1]:
import torch
from torchvision import transforms
from msrvtt_dataset import MSRVTTDataset as MSRVTT
from msrvtt_dataset import Standardize_VideoSentencePair, ToTensor_VideoSentencePair
from utils.train_utils import get_dataloader

repo_dir = '/usr/local/extstore01/zahra/datasets/MSRVTT/'
video_feats_dir = f'{repo_dir}/feats/video/r2plus1d_TrainVal'
text_feats_path = f'{repo_dir}/feats/text/msrvtt_captions_np.pkl'
ids_path = f'{repo_dir}/TrainVal_videoid_sentid.txt'

dl_params = {'batch_size': 64,
             'shuffle': False,
             'num_workers': 1}


In [3]:
dataset0 = MSRVTT(vid_feats_dir=video_feats_dir, txt_feats_path=text_feats_path, ids_path=ids_path, transform=None)
dataset_stats = dataset0.get_dataset_mean_std()
standardize = Standardize_VideoSentencePair(dataset_stats)
trnsfrm = transforms.Compose([standardize,
                              ToTensor_VideoSentencePair()])
dataset1 = MSRVTT(vid_feats_dir=video_feats_dir, txt_feats_path=text_feats_path, ids_path=ids_path, transform=trnsfrm)


In [4]:
dataloader0 = torch.utils.data.DataLoader(dataset0, **dl_params)
dataloader1 = torch.utils.data.DataLoader(dataset1, **dl_params)

In [5]:
for v,t in dataloader0:
    print(v.sum(axis=1))
    print(t.sum(axis=1))
    break

tensor([384.0339, 384.0339, 384.0339, 384.0339, 384.0339, 384.0339, 384.0339,
        384.0339, 384.0339, 384.0339, 384.0339, 384.0339, 384.0339, 384.0339,
        384.0339, 384.0339, 384.0339, 384.0339, 384.0339, 384.0339, 295.4547,
        295.4547, 295.4547, 295.4547, 295.4547, 295.4547, 295.4547, 295.4547,
        295.4547, 295.4547, 295.4547, 295.4547, 295.4547, 295.4547, 295.4547,
        295.4547, 295.4547, 295.4547, 295.4547, 295.4547, 305.2802, 305.2802,
        305.2802, 305.2802, 305.2802, 305.2802, 305.2802, 305.2802, 305.2802,
        305.2802, 305.2802, 305.2802, 305.2802, 305.2802, 305.2802, 305.2802,
        305.2802, 305.2802, 305.2802, 305.2802, 376.5073, 376.5073, 376.5073,
        376.5073])
tensor([-0.1561, -0.1257,  0.1872, -1.0136, -0.1572, -0.4226,  0.0253, -0.7116,
         0.5344, -0.9168,  0.6959,  0.1373,  0.1440, -1.1415, -1.1937, -1.3953,
         0.6959,  0.5344, -0.1561, -0.1257,  1.3657,  0.4104,  1.8833,  0.8749,
         2.1915,  0.8295,  1.6187,  0.9

In [16]:
for v,t in dataloader1:
    print(v[0])
    print(v[10])
    
    print(v[0])
    print(t[0])
#     print(v.sum(axis=-1))
#     print(t.sum(axis=-1))
#     print(v.shape)
#     print(t.shape)
    break

/usr/local/extstore01/zahra/VTR_OOD/msrvtt_dataset.py:132: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  v = torch.tensor(v)
/usr/local/extstore01/zahra/VTR_OOD/msrvtt_dataset.py:133: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t = torch.tensor(t)


tensor([-1.1926,  0.6817,  0.2575,  ..., -0.5511, -0.8556,  0.1798])
tensor([-1.1926,  0.6817,  0.2575,  ..., -0.5511, -0.8556,  0.1798])
tensor([-1.1926,  0.6817,  0.2575,  ..., -0.5511, -0.8556,  0.1798])
tensor([-1.6907e-01,  1.1798e+00, -1.4095e+00, -1.9838e-01, -1.2182e+00,
        -7.8848e-01,  4.5310e-01,  6.9591e-02, -6.3659e-04,  1.0359e+00,
         1.6540e+00,  1.3555e+00, -1.2439e+00, -1.4489e-01,  5.0111e-01,
        -4.1846e-01,  2.5158e-01,  1.7326e+00, -6.3071e-01,  1.3111e-01,
        -1.1567e+00, -1.2790e+00, -6.9632e-01,  1.2733e+00,  6.7060e-01,
        -1.3324e-01, -9.6347e-02,  2.5007e-01,  6.0387e-02, -1.8082e-01,
        -1.6076e+00, -1.5603e-01,  4.6038e-01, -7.6437e-02, -8.6120e-01,
         5.3417e-01, -1.5458e-01, -5.8902e-01, -1.3409e+00,  1.1857e+00,
         8.1478e-01,  4.3629e-01, -7.2577e-01, -1.5572e-02, -1.2651e+00,
        -1.4165e+00, -9.7087e-01, -9.8241e-01,  1.2515e+00,  7.3153e-01,
         1.3227e+00, -9.4711e-01,  1.1537e+00,  5.3217e-01,  6.